name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build
        run: |
          npm install
          npm i @parcel/watcher
          npm i lightningcss
          npm i @swc/core
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: server/public
      - uses: actions/upload-pages-artifact@v1
        with:
          path: server/public

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment